project_name: etcdviewer
release:
  github:
    owner: double12gzh
    name: etcdviewer
builds:
  - id: etcdviewer
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/etcdviewer/main.go
    ldflags: -s -w
      -X github.com/double12gzh/etcdviewer/pkg/version.version=
archives:
  - id: etcdviewer
    builds:
    - etcdviewer
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
